--- #YAML:1.0
name:               Module-Find
version:            '0.15'
provides:
  Module::Find:
    file: Find.pm
    version: '0.15'
abstract:           Find and use installed modules in a (sub)category
author:
    - Christian Renz <crenz@web42.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Find:  0
    File::Spec:  0
    perl:        5.006001
    Test::More:  0
resources:
    repository:  http://github.com/crenz/Module-Find
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    Test::Pod:            1.14
    Test::Pod::Coverage:  1.04
