name: Run tests on master (matrixed)

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        perl: [ '5', '5.32', '5.8.1' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Identify perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --installdeps .
      - run: cpanm Test::Pod 
      - run: cpanm Test::Pod::Coverage
      - run: cpanm Test::CPAN::Meta
      - name: Run tests
        run: make test TEST_VERBOSE=1
  test-strawberry:
    runs-on: 'windows-latest'
    strategy:
      matrix:
        perl: [ '5', '5.32' ]
    name: Perl ${{ matrix.perl }} on windows-latest (strawberry)
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Identify perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --installdeps .
      - name: Run tests
        run: make test TEST_VERBOSE=1
