name: Tests (perl 5.8, Ubuntu/Mac)

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']
        perl: [ '5.8.9', '5.8.1' ]
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - name: Identify perl version
        run: perl -V
      - name: Install dependencies
        run: cpanm --installdeps .
      - name: Run tests
        run: make test TEST_VERBOSE=1
